/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tubes;

import Tubes.TBA;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Admin123
 */
public class View extends javax.swing.JFrame implements ActionListener{    
    
    public View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlParser = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfStatusParser = new javax.swing.JTextField();
        tfKalimatParser = new javax.swing.JTextField();
        btnCek = new javax.swing.JButton();
        btnResetParser = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        tfSub1 = new javax.swing.JTextField();
        tfPre1 = new javax.swing.JTextField();
        tfObj1 = new javax.swing.JTextField();
        tfKet1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 102));

        pnlParser.setBackground(new java.awt.Color(0, 102, 255));
        pnlParser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlParser.setPreferredSize(new java.awt.Dimension(350, 136));

        jLabel2.setText("Masukkan Kalimat");

        jLabel3.setText("Status Kalimat");

        tfStatusParser.setEditable(false);
        tfStatusParser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfStatusParserActionPerformed(evt);
            }
        });

        tfKalimatParser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfKalimatParserActionPerformed(evt);
            }
        });

        btnCek.setText("Check");
        btnCek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekActionPerformed(evt);
            }
        });

        btnResetParser.setText("Reset");
        btnResetParser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetParserActionPerformed(evt);
            }
        });

        btnExit.setText("Keluar");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        tfSub1.setEditable(false);
        tfSub1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSub1ActionPerformed(evt);
            }
        });

        tfPre1.setEditable(false);
        tfPre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPre1ActionPerformed(evt);
            }
        });

        tfObj1.setEditable(false);
        tfObj1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfObj1ActionPerformed(evt);
            }
        });

        tfKet1.setEditable(false);
        tfKet1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfKet1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Subjek");

        jLabel5.setText("Predikat");

        jLabel6.setText("Objek");

        jLabel7.setText("Keterangan");

        jLabel8.setText("Kalimat harus diakhiri dengan titik (.)");

        jScrollPane1.setBackground(new java.awt.Color(51, 255, 51));

        jTable1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"kamu", "menjaga", "laporan   ", "kemarin   "},
                {"saya", "melestarikan", "proyek   ", "besok"},
                {"mahasiswa", "bermain", "tanaman   ", "di perpustakaan"},
                {"dosen", "bekerja ", "laptop   ", "di laboratorium"},
                {"petugas", "belajar", "gitar ", "di kelas"}
            },
            new String [] {
                "Subjek", "Predikat", "Objek", "Predikat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout pnlParserLayout = new javax.swing.GroupLayout(pnlParser);
        pnlParser.setLayout(pnlParserLayout);
        pnlParserLayout.setHorizontalGroup(
            pnlParserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlParserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlParserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlParserLayout.createSequentialGroup()
                        .addComponent(btnExit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnResetParser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCek))
                    .addGroup(pnlParserLayout.createSequentialGroup()
                        .addGroup(pnlParserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlParserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlParserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfStatusParser)
                            .addComponent(tfKalimatParser)
                            .addGroup(pnlParserLayout.createSequentialGroup()
                                .addGroup(pnlParserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfSub1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(tfPre1)
                                    .addComponent(tfObj1)
                                    .addComponent(tfKet1))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(pnlParserLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlParserLayout.setVerticalGroup(
            pnlParserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlParserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlParserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfKalimatParser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlParserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfStatusParser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlParserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSub1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlParserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlParserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfObj1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlParserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfKet1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlParserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCek)
                    .addComponent(btnResetParser)
                    .addComponent(btnExit))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 449, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlParser, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlParser, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfStatusParserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfStatusParserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfStatusParserActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(1);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnResetParserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetParserActionPerformed
        setTfKalimatParser("");
        setTfStatusParser("");
        setTfSub1("");
        setTfPre1("");
        setTfObj1("");
        setTfKet1("");
    }//GEN-LAST:event_btnResetParserActionPerformed

    private void btnCekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekActionPerformed
             
    }//GEN-LAST:event_btnCekActionPerformed

    private void tfSub1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSub1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSub1ActionPerformed

    private void tfPre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPre1ActionPerformed

    private void tfObj1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfObj1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfObj1ActionPerformed

    private void tfKet1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfKet1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfKet1ActionPerformed

    private void tfKalimatParserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfKalimatParserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfKalimatParserActionPerformed

    
    public String getTfKalimatParser() {
        return tfKalimatParser.getText();
    }

    public void setTfKalimatParser(String tfKalimatParser) {
        this.tfKalimatParser.setText(tfKalimatParser);
    }
    
    public String getTfStatusParser() {
        return tfStatusParser.getText();
    }

    public void setTfStatusParser(String x) {
        this.tfStatusParser.setText(x);
    }

    public String getTfKet1() {
        return tfKet1.getText();
    }

    public void setTfKet1(String tfKet1) {
        this.tfKet1.setText(tfKet1);
    }

    public String getTfObj1() {
        return tfObj1.getText();
    }

    public void setTfObj1(String tfObj1) {
        this.tfObj1.setText(tfObj1);
    }

    public String getTfPre1() {
        return tfPre1.getText();
    }

    public void setTfPre1(String tfPre1) {
        this.tfPre1.setText(tfPre1);
    }

    public String getTfSub1() {
        return tfSub1.getText();
    }

    public void setTfSub1(String tfSub1) {
        this.tfSub1.setText(tfSub1);
    }

    public JButton getBtnCek() {
        return btnCek;
    }

    public JButton getBtnExit() {
        return btnExit;
    }

    public JButton getBtnResetParser() {
        return btnResetParser;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCek;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnResetParser;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel pnlParser;
    private javax.swing.JTextField tfKalimatParser;
    private javax.swing.JTextField tfKet1;
    private javax.swing.JTextField tfObj1;
    private javax.swing.JTextField tfPre1;
    private javax.swing.JTextField tfStatusParser;
    private javax.swing.JTextField tfSub1;
    // End of variables declaration//GEN-END:variables

    public void addActionListener(ActionListener e) {
        btnCek.addActionListener(e);
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        Object source = e.getSource();
        if(source.equals(getBtnCek())){
            btnCekActionPerformed(e);
        }
    }
}
